/* 
 * Every file you submit should start with a header like this!
 * 
 * File:    Negotiation.c
 * Author: Gurpinder Singh (gujsingh@ucsc.edu)
 *
 * Created on May 30, 2020, 7:10 PM
 */
// **** Include libraries here ****
// Standard libraries
#include <stdio.h>
#include "BOARD.h"
#include "Negotiation.h"
int Parity(NegotiationData A);
/**
 * This function implements a one-way hash.  It maps its input, A, 
 * into an image, #a, in a way that is hard to reverse, but easy 
 * to reproduce.
 * @param secret        //A number that a challenger commits to
 * @return hash         //the hashed value of the secret commitment.
 *
 * This function implements the "Beef Hash," a variant of a Rabin hash.
 * The result is ((the square of the input) modulo the constant key 0xBEEF).
 * So, for example, 
 * 
 * NegotiationHash(3) == 9
 * NegotiationHash(12345) == 43182
 */
NegotiationData NegotiationHash(NegotiationData secret) {
    return (NegotiationData) ((secret*secret) % PUBLIC_KEY);
}

/**
 * Detect cheating.  An accepting agent will receive both a commitment hash
 * and a secret number from the challenging agent.  This function
 * verifies that the secret and the commitment hash agree, hopefully
 * detecting cheating by the challenging agent.
 *
 * @param secret        //the previously secret number that the challenging agent has revealed
 * @param commitment    //the hash of the secret number
 * @return TRUE if the commitment validates the revealed secret, FALSE otherwise
 */
int NegotiationVerify(NegotiationData secret, NegotiationData commitment) {
    if (commitment == NegotiationHash(secret)) {
        return TRUE;
    }
    return FALSE;
}

/**
 * The coin-flip protocol uses random numbers generated by both
 * agents to determine the outcome of the coin flip.
 *
 * The parity of a bitstring is 1 if there are an odd number of one bits,
 *   and 0 otherwise.
 * So, for example, the number 0b01101011 has 5 ones.  If the parity of
 * A XOR B is 1, then the outcome is HEADS.  Otherwise, the outcome is TAILS.
 */
NegotiationOutcome NegotiateCoinFlip(NegotiationData A, NegotiationData B) {
    if (Parity((NegotiationData) (A^B))) {
        return HEADS;
    }
    return TAILS;
}
//calculates the parity
int Parity(NegotiationData A) {
    int bitcount = 0;
    //loops through and checks if a bite is zero or 1 through anding
    while (A) {
        if (A & 1) {
            bitcount += 1;
        }
        A = A >> 1;
    }
    return bitcount % 2;
}

